### PR TITLE
- Fixes #5

### LINKED ISSUE #5: Handle cases where everyone leaves the game/no votes are cast
Server crashes when trying to read votes after everyone has left/possibly just in the case that the current day/night ends and no votes were cast at all.

bug example

### PR DESCRIPTION
**Pull request by epinapala**
Add an undefined check on results[0] before accessing results[0].votes

### CODE REVIEW

**Comment by epinapala** [comment]
@rustinlee Can you take a look?

**Comment by rustinlee** [comment]
Sorry for the delay, this is a really old project I don't maintain any more -- I'll go ahead and give you push access but your time might be better spent re-writing this from scratch with current frameworks/methodologies. As far as I know a lot of the message transport logic is predicated on the pre-1.0 socket.io API which is probably 2 years old at this point, which is just one example of how outdated this codebase is.

**Comment by epinapala** [comment]
@rustinlee Thanks for the response. I am thinking to rewrite this as a slack bot. That way We can concentrate on engine logic and worry less about UI. If I do use any fo your components, I will mention you in credits. Thanks for the great work!

**Comment by rustinlee** [comment]
That's a great idea; I would love to play Mafia in slack. Please keep me
updated!

**Comment by epinapala** [comment]
Here is what I have so far - https://github.com/epinapala/mafiabot, still a lot more to do :)

**Pull request merged**
